version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: codearena_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  mongodb:
    image: mongo:6
    container_name: codearena_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
